ЗАДАНИЕ 1 NUMPY

In [126]:
import numpy as np

№1. Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7

In [127]:
a=np.array([[1, 6], [2,8], [3,11], [3,10], [1,7]])

In [128]:
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [129]:
mean1=np.mean(a[:,0])
mean2=np.mean(a[:,1])
a_mean=(mean1,mean2)

In [130]:
print(a_mean)

(2.0, 8.4)


№2. Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [131]:
a_centered=a-a_mean

In [132]:
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


№3. Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [133]:
a_centered_sp=np.dot(a_centered[:,0], a_centered[:,1])

In [134]:
print(a_centered_sp)

8.0


In [135]:
N=5 #5 строк
a_centered_sp=a_centered_sp/(N-1)

In [136]:
print(a_centered_sp)

2.0


№5. Проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”

In [137]:
a1=a.transpose()

In [138]:
print(a1)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


In [139]:
a_centered_sp_1=np.cov(a1)

In [140]:
print(a_centered_sp_1[1,0])

2.0


Значения совпадают

##ЗАДАНИЕ 2 PANDAS№№

In [141]:
import pandas as pd

№1.  Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].

In [142]:
author_id=[1, 2, 3]
author_name=['Тургенев', 'Чехов', 'Островский']
authors=pd.DataFrame({'author_id': author_id, 'author_name':author_name})

In [143]:
print(authors)

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский


Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные

In [144]:
author_id=[1, 1, 1, 2, 2, 3, 3]
book_title=['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники']
price=[450, 300, 350, 500, 450, 370, 290]
book=pd.DataFrame({'book_title': book_title, 'author_id':author_id,'price':price})

In [145]:
print(book)

             book_title  author_id  price
0           Отцы и дети          1    450
1                 Рудин          1    300
2     Дворянское гнездо          1    350
3      Толстый и тонкий          2    500
4       Дама с собачкой          2    450
5                 Гроза          3    370
6  Таланты и поклонники          3    290


№2. Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [146]:
authors_price=pd.merge(book,authors, on='author_id', how='inner')

In [147]:
print(authors_price)

             book_title  author_id  price author_name
0           Отцы и дети          1    450    Тургенев
1                 Рудин          1    300    Тургенев
2     Дворянское гнездо          1    350    Тургенев
3      Толстый и тонкий          2    500       Чехов
4       Дама с собачкой          2    450       Чехов
5                 Гроза          3    370  Островский
6  Таланты и поклонники          3    290  Островский


№3. Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [148]:
authors_price=authors_price.sort_values(by='price', ascending=False).reset_index(drop='False')

In [149]:
authors_price

book_title  author_id  price author_name
0      Толстый и тонкий          2    500       Чехов
1           Отцы и дети          1    450    Тургенев
2       Дама с собачкой          2    450       Чехов
3                 Гроза          3    370  Островский
4     Дворянское гнездо          1    350    Тургенев
5                 Рудин          1    300    Тургенев
6  Таланты и поклонники          3    290  Островский

In [150]:
top5=authors_price.loc[0:5,:]

In [151]:
print(top5)

          book_title  author_id  price author_name
0   Толстый и тонкий          2    500       Чехов
1        Отцы и дети          1    450    Тургенев
2    Дама с собачкой          2    450       Чехов
3              Гроза          3    370  Островский
4  Дворянское гнездо          1    350    Тургенев
5              Рудин          1    300    Тургенев


№4. Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца: author_name, min_price, max_price и mean_price,

In [171]:
authors_stat=authors_price.groupby('author_name').agg({'price':['max','min','mean']})
authors_stat=authors_stat.rename(columns={'price':'','max':'max_price','min':'min_price','mean':'mean_price'})
authors_stat

max_price min_price  mean_price
author_name                                
Островский        370       290  330.000000
Тургенев          450       300  366.666667
Чехов             500       450  475.000000

In [ ]:
№5. Создайте новый столбец в датафрейме authors_price под названием cover

In [173]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

book_title  author_id  price author_name    cover
0      Толстый и тонкий          2    500       Чехов  твердая
1           Отцы и дети          1    450    Тургенев   мягкая
2       Дама с собачкой          2    450       Чехов   мягкая
3                 Гроза          3    370  Островский  твердая
4     Дворянское гнездо          1    350    Тургенев  твердая
5                 Рудин          1    300    Тургенев   мягкая
6  Таланты и поклонники          3    290  Островский   мягкая

Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.

In [182]:
book_info=pd.pivot_table(authors_price, values='price', index=['author_name'],
                    columns=['cover'], aggfunc=np.sum)
book_info

cover        мягкая  твердая
author_name                 
Островский      290      370
Тургенев        750      350
Чехов           450      500

Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [183]:
book_info.to_pickle(("./book_info.pkl"))

In [185]:
book_info2 = pd.read_pickle("./book_info.pkl")
book_info2

cover        мягкая  твердая
author_name                 
Островский      290      370
Тургенев        750      350
Чехов           450      500